#!/bin/bash

########################
#                      #
#       WARNING        #
#                      #
#  This script is      #
#  NOT intended for    #
#  modification in the #
#  Kali in Batch       #
#  environment. It is  #
#  overwritten when    #
#  you boot Kali in    #
#  Batch.              #
#                      #
#  To add your own     #
#  configurations,     #
#  modify ~/.bashrc    #
#  instead.            #
#                      #
########################

## Kali Linux shell prompt ##

# Check if ROOT is 1

if [ "$ROOT" == "1" ]; then
    PS1=$'\[\e[34m\]┌──(\[\e[31m\]root㉿\h\[\e[34m\])-[\[\e[0m\]\w\[\e[34m\]]\n\[\e[34m\]└─\[\e[31m\]# \[\e[0m\]'
else
    PS1=$'\[\e[32m\]┌──(\[\e[34m\]\u㉿\h\[\e[32m\])-[\[\e[0m\]\w\[\e[32m\]]\n\[\e[32m\]└─\[\e[34m\]\$ \[\e[0m\]'
fi

alias pkg="$kaliroot/usr/bin/pkg.bat"
alias clear="$kaliroot/usr/bin/clear.bat"
alias touch="$kaliroot/usr/bin/touch.bat"
alias uname="$kaliroot/usr/bin/uname.bat"
alias which="$kaliroot/usr/bin/which.bat"
alias whoami="$kaliroot/usr/bin/whoami.bat"
alias netcat="nc"

## Load ~/.bashrc ##

source ~/.bashrc
