name: Ollama PR Comment

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  ollama-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read  # comment posting is done with app token, not GITHUB_TOKEN
    
    steps:
      - name: Checkout code (base repo only, safe)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          
      - name: Start Ollama service
        run: |
          ollama serve &
          sleep 4
          ollama pull llama3.2:3b


      - name: Get PR diff safely
        id: pr-diff
        run: |
          PR_NUM=${{ github.event.pull_request.number }}
          curl -sSL -o pr.diff https://github.com/${{ github.repository }}/pull/${PR_NUM}.diff
          head -n 3000 pr.diff > limited_diff.txt

      - name: Generate comment with Ollama
        id: generate-comment
        run: |
          cat > prompt.txt << 'EOF'
          Please review this pull request diff and provide constructive feedback. 
          Focus on:
          - Code quality and best practices
          - Potential bugs or issues
          - Suggestions for improvement
          - Security considerations if applicable
          
          Keep your response concise and helpful. Format it as markdown. Lines starting with "-" are REMOVED lines, Lines starting with "+" are ADDED lines. ONLY FOCUS ON REMOVED AND ADDED LINES.
          
          Here's the diff:
          EOF
          
          cat limited_diff.txt >> prompt.txt
          
          COMMENT=$(ollama run llama3.2:3b "$(cat prompt.txt)")
          echo "$COMMENT" > comment.txt
          echo "Generated comment:"
          echo "$COMMENT"

      # Authenticate as GitHub App
      - name: Authenticate GitHub App
        id: auth
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Post comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.auth.outputs.token }}
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('comment.txt', 'utf8');
            
            const fullComment = `## 🤖 AI Code Review (Ollama)
            
            ${comment}
            
            ---
            *This comment was generated by Ollama running in GitHub Actions*`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fullComment
            });

      - name: Cleanup
        if: always()
        run: |
          pkill -f ollama || true
          rm -f pr_diff.txt limited_diff.txt prompt.txt comment.txt

  ollama-reply:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body, '@ollama-comment') &&
      github.event.issue.pull_request
    permissions:
      issues: write
      pull-requests: write
      contents: read

    steps:
      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      - name: Start Ollama service
        run: |
          ollama serve &
          sleep 4
          ollama pull llama3.2:3b

      - name: Generate reply with Ollama
        id: generate-reply
        run: |
          USER_COMMENT="${{ github.event.comment.body }}"
          PROMPT="You are Ollama bot. This GitHub comment mentioned you: \"${USER_COMMENT}\". Reply helpfully and concisely in markdown."
          REPLY=$(ollama run llama3.2:3b "$PROMPT")
          echo "$REPLY" > reply.txt

      - name: Authenticate GitHub App
        id: auth
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Post threaded reply
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.auth.outputs.token }}
          script: |
            const fs = require('fs');
            const reply = fs.readFileSync('reply.txt', 'utf8');
            const targetCommentId = context.payload.comment.id;

            const fullReply = `## 🤖 Ollama Bot Reply

            ${reply}

            ---
            *This reply was generated by Ollama running in GitHub Actions*`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: fullReply,
              in_reply_to: targetCommentId
            });

      - name: Cleanup
        if: always()
        run: |
          pkill -f ollama || true
          rm -f reply.txt
