name: Ollama PR Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ollama-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          
      - name: Start Ollama service
        run: |
          # Start ollama in the background
          ollama serve &
          
          # Wait for ollama to be ready
          sleep 10
          
          # Pull the model
          ollama pull llama3.2:3b

      - name: Get PR diff
        id: pr-diff
        run: |
          # Get the diff for the PR
          git diff origin/${{ github.base_ref }}..HEAD > pr_diff.txt
          
          # Limit diff size to avoid token limits (first 3000 lines)
          head -n 3000 pr_diff.txt > limited_diff.txt

      - name: Generate comment with Ollama
        id: generate-comment
        run: |
          # Create a prompt for code review
          cat > prompt.txt << 'EOF'
          Please review this pull request diff and provide constructive feedback. 
          Focus on:
          - Code quality and best practices
          - Potential bugs or issues
          - Suggestions for improvement
          - Security considerations if applicable
          
          Keep your response concise and helpful. Format it as markdown.
          
          Here's the diff:
          EOF
          
          cat limited_diff.txt >> prompt.txt
          
          # Generate response using Ollama
          COMMENT=$(ollama run llama3.2:3b "$(cat prompt.txt)")
          
          # Save comment to file for next step
          echo "$COMMENT" > comment.txt
          
          # Also output for debugging
          echo "Generated comment:"
          echo "$COMMENT"

      - name: Post comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('comment.txt', 'utf8');
            
            // Add a header to identify this as an AI-generated comment
            const fullComment = `## 🤖 AI Code Review (Ollama)
            
            ${comment}
            
            ---
            *This comment was generated by Ollama running in GitHub Actions*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fullComment
            });

      - name: Cleanup
        if: always()
        run: |
          # Kill ollama process
          pkill -f ollama || true
          # Clean up temporary files
          rm -f pr_diff.txt limited_diff.txt prompt.txt comment.txt

