name: Release KIB Batch Standalone
permissions:
  contents: write
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
      
      - name: Build standalone executable
        run: python mkstandalone.py

      - name: Compress ./src to kib_in_batch.zip
        run: Compress-Archive -Path src -DestinationPath kib_in_batch.zip

      - name: Publish Release & Upload Files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/kib-standalone.bat
            kib_in_batch.zip
            LICENSE.txt
            uninstall.bat
            README.md

